version: '3'
services:
  arangodb:
    container_name: arangodb_oop
    image: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=root
    ports:
      - 8529:8529
    volumes:
      - /var/lib/arangodb:/var/lib/arangodb
  schema_service:
    build: 
      context: schema_service/
      dockerfile: Dockerfile
    ports: 
     - 5000:5000